WITH JOINED_USERS AS (
    SELECT 
        USER_ID
    FROM 
        USER_INFO
    WHERE 
        YEAR(JOINED) = 2021
),
PURCHASED_STATS AS (
    SELECT 
        YEAR(SALES_DATE) AS YEAR,
        MONTH(SALES_DATE) AS MONTH,
        COUNT(DISTINCT USER_ID) AS PURCHASED_USERS
    FROM 
        ONLINE_SALE
    WHERE 
        USER_ID IN (SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED) = 2021)
    GROUP BY 
        YEAR(SALES_DATE), MONTH(SALES_DATE)
)
SELECT 
    PS.YEAR,
    PS.MONTH,
    PS.PURCHASED_USERS,
    ROUND(PS.PURCHASED_USERS / (SELECT COUNT(*) FROM JOINED_USERS), 1) AS PURCHASED_RATIO
FROM 
    PURCHASED_STATS PS
ORDER BY 
    PS.YEAR ASC, PS.MONTH ASC;